### ISSUE TITLE
Add interface support for types in config

### ISSUE THREAD

**Issue by shellforge** [warpforge/warpgrapher#20]
When a lot of types share some common attributes, it would be useful to have an interface/prototype to centrally manage common attributes.

Ex:

```
name: Soldier
props:
  name: String
  health: Int
  speed: Int
  damage: Int

name: Explorer
props:
  name: String
  health: Int
  speed: Int
  visibility: Int
```

Can be replaced with:

```
name: CharacterClass
prototype: true
props:
  name: String
  health: Int
  speed: Int

name: Soldier
implements: CharacterClass
props:
  damage: Int

name: Explorer
implements: CharacterClass
props:
  visibility: Int
```

If more attributes to the CharacterClass need to be added, they can be managed in a central location instead of adding them to every individual type. 

From an implementation point of view, the "prototype" type is not part of the GraphQL schema / model. The attributes (props and rels) derived from a "prototype" type are added during config initialization. This concept would only exist inside methods of WarpgrapherConfig, and the rest of warpgrapher would remain unaware of this.
