### ISSUE TITLE
List param ignored when prop is Scalar

### ISSUE THREAD

**Issue by shellforge** [warpforge/warpgrapher#24]
Given the following WarpgrapherType yaml config:

```yaml
name: MyType
props: 
  - name: name
    type: String
  - name: desc
    type: String
  - name: keys
    type: String
    list: true
  - name: values
    type: String
    list: true
```

The props `keys` and `values` are created as type non-list Strings despite the `list: true` flag.
