### ISSUE TITLE
Query fragments on multi-type rel panics

### ISSUE THREAD

**Issue by shellforge** [warpforge/warpgrapher#42]
The following query:

```
query {
  Project {
    id
    name
    issues {
      dst {
        ... on Feature {
          name
          points
        }
      }
    }
  }
}
```

Given the following config:

```yaml
version: 1
model:

 # Project
  - name: Project
    props:
      - name: name
        type: String
    rels:
      - name: issues
        props:
          - name: since
            type: String
        nodes: [Feature, Bug]
        list: true
  
  # Feature
  - name: Feature
    props:
      - name: name
        type: String
      - name: points
        type: Int
  
  # Bug
  - name: Bug
    props:
      - name: name
        type: String
      - name: critical
        type: Boolean
``` 

Returns the following error:

```
thread 'actix-rt:worker:0' panicked at 'Field points not found on type Some("Bug")', <::std::macros::panic macros>:2:4
```

It seems like the resolver is attempting to read the fields of `Feature` on a `Bug` node.
